AES: AES.cpp
	g++ -I.. -I../cryptopp AES.cpp ../cryptopp/libcryptopp.a -std=c++11 -O2 -o AES.o

onsite: onsite.cpp
	g++ -I.. -I../cryptopp onsite.cpp ../cryptopp/libcryptopp.a -std=c++11 -O2 -o onsite.o